### PR TITLE
Merge remote-tracking branch 'refs/remotes/andres-erbsen/master'

### PR DESCRIPTION
**Pull request by kaabre**
chill schedule update

### CODE REVIEW

**Comment by andres-erbsen** [comment]
It would be really nice if the time column did not get split across multiple lines automatically; either manually split it or disable it. That's just a nice-to-have, though.

**Comment by kaabre** [comment]
Ah.  Well, i don't really have time to fix any of this unless totally
necessary, since I'm flying out soon.

Is it merged/ok?  anything else i need to do?  it's not up on the website
yet

**Comment by andres-erbsen** [comment]
kaabre <notifications@github.com> writes:

> Ah.  Well, i don't really have time to fix any of this unless totally
> necessary, since I'm flying out soon.
>
> Is it merged/ok?  anything else i need to do?  it's not up on the website
> yet

I merged the version from your clone of repository committed half hour
ago, and it should be on the website now. Friendly notice: it is 2017
now (fixed).

**Comment by kaabre** [comment]
whoops thanks

**Pull request merged**
